[xxx] Fixes db:migrate error
there is already an index from train.record_type
```
bundle exec rails db:migrate
== 20201022154840 AddIndexToRecordType: migrating =============================
-- add_index(:trainees, :record_type)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_trainees_on_record_type' on table 'trainees' already exists
/Users/Work/register-trainee-teacher-data/db/migrate/20201022154840_add_index_to_record_type.rb:3:in `change'
bin/rails:4:in `<main>'

Caused by:
ArgumentError: Index name 'index_trainees_on_record_type' on table 'trainees' already exists
/Users/Work/register-trainee-teacher-data/db/migrate/20201022154840_add_index_to_record_type.rb:3:in `change'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```